Move scripts to Dockerfiles

diff --git a/ffmpeg/Dockerfile b/ffmpeg/Dockerfile
--- a/ffmpeg/Dockerfile
+++ b/ffmpeg/Dockerfile
@@ -10,8 +10,78 @@ ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
 # FFMPEG package deps
 RUN apt-get -y install libmp3lame-dev libxvidcore-dev libxml2-utils libass-dev libgpac-dev libtheora-dev libtool libvorbis-dev 
 
-ADD install_ffmpeg.sh /install_ffmpeg.sh
-RUN /install_ffmpeg.sh
+RUN apt-get install -y bzip2 make gcc gcc-c++ automake autoconf libtool yasm nasm git
 
-ADD install_exiftool.sh /install_exiftool.sh
-RUN /install_exiftool.sh
+	export LD_LIBRARY_PATH=/usr/local/lib/
+	echo /usr/local/lib > /etc/ld.so.conf.d/custom-libs.conf
+	ldconfig
+
+	curl -L http://downloads.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-0.1.3.tar.gz | tar zxf -
+	if [ $? -ne 0 ]; then echo "opencore-amr download failed"; exit 1; fi
+	cd opencore-amr-0.1.3
+	./configure
+	make && make install
+	ldconfig
+	cd ..
+	rm -rf opencore-amr-0.1.3
+
+	curl -L http://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-0.1.3.tar.gz | tar zxf -
+	if [ $? -ne 0 ]; then echo "fdk-aac download failed"; exit 1; fi
+	cd fdk-aac-0.1.3
+	./configure
+	make && make install
+	ldconfig
+	cd ..
+	rm -rf fdk-aac-0.1.3
+
+	curl -L http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz | tar zxf -
+	if [ $? -ne 0 ]; then echo "ogg download failed"; exit 1; fi
+	cd libogg-1.3.2
+	./configure
+	make && make install
+	ldconfig
+	cd ..
+	rm -rf libogg-1.3.2
+
+	git clone git://git.videolan.org/x264.git
+	if [ $? -ne 0 ]; then echo "x264 download failed"; exit 1; fi
+	cd x264
+	./configure --enable-shared
+	make && make install
+	ldconfig
+	cd ..
+	rm -rf x264
+
+	curl -L https://webm.googlecode.com/files/libvpx-v1.3.0.tar.bz2 | tar xjf -
+	if [ $? -ne 0 ]; then echo "vpx download failed"; exit 1; fi
+	cd libvpx-v1.3.0
+	./configure --enable-shared
+	make && make install
+	ldconfig
+	cd ..
+	rm -rf libvpx-v1.3.0
+
+	curl -L http://ffmpeg.org/releases/ffmpeg-2.7.2.tar.bz2 | tar xjf -
+	if [ $? -ne 0 ]; then echo "ffmpeg download failed"; exit 1; fi
+	cd ffmpeg
+	./configure --enable-avfilter --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb \
+		--enable-libvpx --enable-libfdk_aac --enable-libmp3lame --enable-libtheora --enable-libvorbis \
+		--enable-libx264 --enable-libxvid --enable-gpl --enable-postproc --enable-nonfree --enable-shared
+	make && make install
+	ldconfig
+	cd tools
+	make qt-faststart
+	cp qt-faststart /usr/local/bin
+	ldconfig
+	cd ../..
+	rm -rf ffmpeg
+
+RUN apt-get install -y perl-ExtUtils-MakeMaker
+
+	curl -L http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-9.84.tar.gz | tar zxf -
+	if [ $? -ne 0 ]; then echo "exiftool download failed"; exit 1; fi
+	cd Image-ExifTool-9.84
+	perl Makefile.PL
+	make && make install
+	cd ..
+	rm -rf Image-ExifTool-9.84
diff --git a/opencv/Dockerfile b/opencv/Dockerfile
--- a/opencv/Dockerfile
+++ b/opencv/Dockerfile
@@ -4,8 +4,27 @@ MAINTAINER Ryan Versaw <ryan.versaw@hudl.com>
 
 RUN apt-get update -y
 
-ADD install_opencv.sh /install_opencv.sh
-RUN /install_opencv.sh
+RUN cd  /
 
-ADD install_gsl.sh /install_gsl.sh
-RUN /install_gsl.sh
+	apt-get install -y cmake
+	git clone https://github.com/Itseez/opencv
+	git clone https://github.com/Itseez/opencv_contrib
+	if [ $? -ne 0 ]; then echo "opencv download failed"; exit 1; fi
+	cd opencv
+	cmake -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules .
+	make && make install
+	ldconfig
+	cd ..
+	rm -rf opencv
+	rm -rf opencv_contrib
+
+RUN cd  /
+
+	curl -L http://gnu.mirrorcatalogs.com/gsl/gsl-1.16.tar.gz | tar zxf -
+	if [ $? -ne 0 ]; then echo "gsl download failed"; exit 1; fi
+	cd gsl-1.16
+	./configure
+	make && make install
+	ldconfig
+	cd ..
+	rm -rf gsl-1.16
